version: "3.5"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - /opt/nginx/conf.d:/etc/nginx/conf.d
      # - /opt/www:/opt/www

  udp-server-1:
    image: golang:1.10
    restart: unless-stopped
    volumes:
      - ./cmd/udp-server:/app/
    entrypoint: go run /app/main.go
    environment:
      - "PORT=1053"

  udp-server-2:
    image: golang:1.10
    restart: unless-stopped
    volumes:
      - ./cmd/udp-server:/app/
    entrypoint: go run /app/main.go
    environment:
      - "PORT=1153"

  udp-client:
    image: golang:1.10
    volumes:
      - ./cmd/udp-client:/app/
    entrypoint: go run /app/main.go
    environment:
      - "UDP_SERVER=nginx:53"
